### ISSUE TITLE
Available on Bower

### ISSUE THREAD

**Issue by nonameolsson** [GabiAxel/paper-dropdown-menu#1]
Is this available to install with Bower? Can't find it when I search for it.

**Comment by GabiAxel** [comment]
Since I'm hoping this ends up as part of PolymerElements, I'm sticking to their convention of not having a dedicated Bower package for the element. You can add it to your bower.json like so:

```
"paper-dropdown-menu": "GabiAxel/paper-dropdown-menu"
```

After getting some feedback, and if it doesn't get into PolymerElements, I'll add a release.

**Comment by nonameolsson** [comment]
Thank you! Now I understand. Thanks for your fast reply.

**Comment by Ortham** [comment]
Thanks for implementing this! Could you please tag it so that `"paper-dropdown-menu": "GabiAxel/paper-dropdown-menu#~1.0"` and similar work, and so that there's a tag that matches the version given in the Bower config?
