### ISSUE TITLE
Uncaught TypeError in usage with Polymer-1.0

### ISSUE THREAD

**Issue by dominik0711** [GabiAxel/paper-dropdown-menu#2]
Hi.

I've tried to integrate your paper-dropdown-menu but I'll always receive the following error:

Uncaught TypeError: Cannot read property 'activateEvent' of undefined

Any suggestions why? I'm using Polymer 1.0.6

**Comment by GabiAxel** [comment]
Please provide a running example and I'll take a look.

**Comment by jasongardnerlv** [comment]
Is the activateEvent listener even necessary?  I had the same issue and made this change:

``` javascript
    ready: function() {
      this.async(function() {
        var paperMenu = Polymer.dom(this).querySelector('paper-menu');
        if (paperMenu) {
          paperMenu.addEventListener(paperMenu.activateEvent, (function() {
            this.close();
          }).bind(this));
        }
      });
    }
```

I'm not seeing any missing behaviors.  I can select an item and the dropdown goes away. I can click outside of the menu and it goes away.  Same for the escape key.

**Comment by GabiAxel** [comment]
Please switch to the official https://github.com/polymerelements/paper-dropdown-menu
This project is discontinued.
